name: "On Issue Comment"
on:
  issue_comment:
    types: [created]
    
jobs:
  pr-comment:
    if: ${{ github.event.issue.pull_request && github.event.issue.state == 'open' }}
    runs-on: ubuntu-latest
    steps:
      - name: Print event
        uses: actions/github-script@v7
        with:
          script: |
            console.log(JSON.stringify(github.event, null, 2));
            
      - name: Checkout pull request
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.issue.number }}/head