name: "On Issue Comment"
on:
  issue_comment:
    types: [created]

permissions:
  actions: write
  pull-requests: read
  contents: read

jobs:
  check-pr-comment:
    if: ${{ github.event.issue.pull_request && github.event.issue.state == 'open' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.issue.number,
            });

            await github.rest.actions.createWorkflowDispatch({
              workflow_id: 'on-pr-comment.yaml',
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: pr.data.head.ref,
              inputs: {
                comment: JSON.stringify(context.payload.comment),
                issue: JSON.stringify(context.payload.issue),
              },
            })
