name: "On PR Comment"
on:
  workflow_dispatch:
    inputs:
      pr-number:
        required: true
        type: string
      pr-ref:
        required: true
        type: string
      pr-head-ref:
        required: true
        type: string
      comment-id:
        required: true
        type: string
      comment-body:
        required: true
        type: string
      comment-url:
        required: true
        type: string
      sender-login:
        required: true
        type: string
      issue-author-login:
        required: true
        type: string

jobs:
  pr-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Print input
        run: |
          echo "Inputs: ${{ toJson(inputs) }}"
