# This workflow is designed to be triggered from the on-issue-comment.yaml workflow
# This workflow should run on the head ref of the PR the comment was posted on
name: "On PR Comment"

on: 
  workflow_dispatch:
    inputs:
      comment:
        description: 'JSON string of the comment payload from the issue_comment event'
        required: true
        type: string
      issue:
        description: 'JSON string of the issue payload from the issue_comment event'
        required: true
        type: string

jobs:
  pr-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Simple trigger
        if: ${{ contains(fromJSON(inputs.comment).body, '!test') }}
        run: |
          echo "Running tests for PR #${{ fromJSON(inputs.issue).number }}"

      - name: Check trigger in script
        uses: actions/github-script@v7
        with:
          script: |
            const commentBody = JSON.parse(inputs.comment).body;
            const issueNumber = JSON.parse(inputs.issue).number;

            if (commentBody.includes('!deploy')) {
              console.log(`Deploying PR #${issueNumber}`);
            } else if (commentBody.includes('!test')) {
              console.log(`Testing PR #${issueNumber}`);
            } else {
              console.log(`No recognized command in comment for PR #${issueNumber}`);
            }

